---
title: "alphapulldown viz"
date: "2024-04-16 (last modified: `r Sys.Date()`)"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
# library(patchwork)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
my_cols = brewer.pal(8,"Dark2")
stage_cols <- RColorBrewer::brewer.pal("Spectral", n = 10)
stage_cols_ss3 <- stage_cols[c(10,9,8,7,2,3,5,6)]
genotype_cols <- RColorBrewer::brewer.pal("Set2", n = 8)[c(1,3,2,8)]
```

## Read data

```{r}
nc <- readRDS("smartseq3_nc/analysis/clustering/data/ss3_nc_wildtype.rds")
```

## check expression of gabpa, ets1, etv4, and etv5b

```{r}
DefaultAssay(nc) <- "RNA"
nc$stage <- factor(nc$stage, levels = c("3ss","6-7ss", "10ss", "12-13ss", "17-18ss", "21-22ss"))
VlnPlot(nc, c("gabpa", "ets1", "etv4", "etv5b", "elk3","fli1a"), group.by = "stage", 
        pt.size = 0, ncol = 4, cols = stage_cols_ss3[-1])
```

```{r}
ggsave("multiome/analysis_newref/alphafold/analysis/figs/vlnplot_ets_TFs.pdf",width = 10, height = 5)
```

## read alpha fold results

```{r}
predictions_with_good_interpae <- read.csv("multiome/analysis_newref/alphafold/output/models20240202/predictions_with_good_interpae.csv")
head(predictions_with_good_interpae)
```

For ETS: ets1 (Q568B4), etv4 (Q9PUQ1), etv5b (F1QK52), gapba (Q9I9E8)

for bhlh: tfec (Q1JQ62), usf1l (Q6P015), usf1 (Q7ZWC6, F1QUA1)

tfap2a (Q6NYI3, F1QUT4)

```{r}
gene2protein <- data.frame(gene = c("ets1","etv2","etv5b","gabpa","tfec","usf1l","usf1","usf1","tfap2a","tfap2a"),
                           protein = c("Q568B4","Q9PUQ1","F1QK52","Q9I9E8","Q1JQ62","Q6P015","Q7ZWC6","F1QUA1","Q6NYI3","F1QUT4"))

# add gene names to results
predictions_with_good_interpae$p1 <- sapply(predictions_with_good_interpae$jobs, function(x) unlist(strsplit(x, "_and_"))[1])
predictions_with_good_interpae$p2 <- sapply(predictions_with_good_interpae$jobs, function(x) unlist(strsplit(x, "_and_"))[2])
predictions_with_good_interpae$g1 <- gene2protein$gene[match(predictions_with_good_interpae$p1, gene2protein$protein)]
predictions_with_good_interpae$g2 <- gene2protein$gene[match(predictions_with_good_interpae$p2, gene2protein$protein)]
predictions_with_good_interpae$name_long <- paste0(predictions_with_good_interpae$g1,"(",
                                                   predictions_with_good_interpae$p1,")_",
                                                   predictions_with_good_interpae$g2,"(",
                                                   predictions_with_good_interpae$p2,")")

```

```{r}
ggplot(predictions_with_good_interpae, aes(y = mpDockQ.pDockQ, x = pi_score)) +
  geom_point() +
  geom_text_repel(aes(label = name_long), vjust = -1) + theme_classic() + xlim(-2.4, 1.4) + ylim(-0.01, 0.9)
```


```{r}
ggsave("multiome/analysis_newref/alphafold/analysis/figs/scatter_pi_vs_mpDockQ.pdf",width = 6, height = 5)
```

```{r}
# Reordering 'name_long' based on 'iptm' values in descending order
predictions_with_good_interpae$name_long <- factor(predictions_with_good_interpae$name_long, 
                                                   levels = predictions_with_good_interpae$name_long[order(predictions_with_good_interpae$iptm, decreasing = FALSE)])

# Creating the lollipop chart
ggplot(predictions_with_good_interpae, aes(x = name_long, y = iptm)) +
  geom_segment(aes(x = name_long, xend = name_long, y = 0, yend = iptm), color = "grey") +  # Draw lines from zero to the value
  geom_point(size = 4, color = "blue") +  # Draw points at the end of the lines
  theme_classic() + coord_flip() +
  labs(x = "Protein Name", y = "ipTM Score", title = "ipTM Scores Ranked by Protein Name")
```

```{r}
ggsave("multiome/analysis_newref/alphafold/analysis/figs/lolipop_iptm.pdf",width = 6, height = 5)
```

## Technical

```{r}
sessionInfo()
```

