---
title: "Clustering all 8 batches - NC only"
author: "Zhiyuan Hu"
date: '2022-09-02 (last modified: `r Sys.Date()`)'
output: 
    prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
library(Signac)
library(patchwork)
library(RColorBrewer)
library(scales)
stage_cols <- RColorBrewer::brewer.pal("Spectral", n = 11)
genotype_cols <- RColorBrewer::brewer.pal("Set2", n = 8)[c(1,2,3,8)]
sample_cols <- RColorBrewer::brewer.pal("Accent", n = 8)
doublet_cols <- RColorBrewer::brewer.pal("Paired", n = 8)[c(6,8,2)]
col.ls <- c(ArchR::ArchRPalettes$stallion, ArchR::ArchRPalettes$bear) # archR color palettes
names(col.ls) <- NULL
```

# Read data

```{r read data}
seu <- readRDS("/ceph/project/tsslab/zhu/multiome/analysis_newref/clustering/rds/seuobj_rna/seu_RNAsoupx_NTNC31037.rds")
seu <- seu[,seu$seurat_clusters %in% c(1,2,3,4,6,7,9,10,12,13,14,15,18,21,22,23,24)]

seu <- seu[,seu[["RNA"]]@data["jhy",] <= 0.5] # remove apoptotic cells
# remove periderm contaminated cells
seu <- seu[,seu[["RNA"]]@data["cyt1",] <= 0.5] 
seu <- seu[,seu[["RNA"]]@data["krt5",] <= 0.5]
seu <- seu[,seu[["RNA"]]@data["cyt1l",] <= 0.5]

saveRDS(colnames(seu) , "multiome/analysis_newref/clustering/rds/subsetting_info/cellnames_multiome18k_NC.rds")

seu$major_clusters_NTnNC <- seu$seurat_clusters

dim(seu)
```

# QC

```{r percent.mt, fig.width=12, fig.height=4}
VlnPlot(
  object = seu,
  features = c("nCount_RNA", "nFeature_RNA", "percent.mt"),
  ncol = 6,
  pt.size = 0, group.by = "sample"
)
```

```{r}
knitr::kable(table(seu$sample))
```

# Seurat pipeline of analysing GEX data

```{r, fig.width=12, fig.height=5}
DefaultAssay(seu) <- "RNA"
seu <- NormalizeData(seu, normalization.method = "LogNormalize", scale.factor = 10000)
seu <- FindVariableFeatures(seu, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(seu), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(seu)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```

```{r}
seu <- ScaleData(seu, features = rownames(seu))
seu <- RunPCA(seu, features = VariableFeatures(object = seu))
# Examine and visualize PCA results a few different ways
print(seu[["pca"]], dims = 1:15, nfeatures = 5)
```

```{r}
VizDimLoadings(seu, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(seu, reduction = "pca", group.by = "sample")
```

```{r}
ElbowPlot(seu, ndims = 50)
```

```{r}
seu <- FindNeighbors(seu, dims = 1:15)
seu <- FindClusters(seu, resolution = 1, algorithm = 1)
seu <- RunTSNE(seu, dims = 1:15)

```

```{r}
FeaturePlot(seu, "elavl3", reduction = "tsne",pt.size = 1)
```

# Clustering results

```{r, fig.height=6, fig.width=20}
# library(RColorBrewer)
# my_cols = brewer.pal(8,"Dark2")
# seu$genotype <- factor(seu$genotype, levels  = c("cit","dp"))
seu$stage <- factor(seu$stage, levels = c("epiboly-4ss","6-10ss","12-16ss","18-22ss"))
p1 <- DimPlot(seu, label = TRUE, reduction = "tsne", cols = alpha(col.ls, 0.3))
p2 <- DimPlot(seu, reduction = "tsne", group.by = "genotype",cols = alpha(genotype_cols, 0.4), pt.size = 0.5)
p3 <- DimPlot(seu, reduction = "tsne", group.by = "stage", cols = alpha(stage_cols[c(2,5,8,10)], 0.4), pt.size = 0.5)
p1 + p2 + p3
```

# Find new markers

```{r findallmarkers}
nc.markers <- FindAllMarkers(seu, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
nc.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC) -> top2
top2
```

# Expression of known marker genes

```{r, fig.height=5, fig.width=16}
FeaturePlot(seu, features = c("foxd3-mCherry","foxd3-citrine","foxd3"), pt.size = 0.1, ncol = 3,  reduction  = 'tsne')
```
```{r}
VlnPlot(seu, features = c("foxd3", "foxd3-mCherry","foxd3-citrine"), group.by =  "sample")
```


```{r expression-known-markers, fig.width=21, fig.height=8}
known_markers <- c("foxd3", "sox10","pax3a","tfap2a",
                   "mafba","egr2b","hoxb3a",
                   "tbxta","sox2","msgn1")
FeaturePlot(seu, features = c(known_markers), ncol = 5, reduction  = 'tsne')
```

```{r expression-known-markers2, fig.width=21, fig.height=8}
known_markers <- c("hoxb2a","hoxa2b", "hoxb3a","hoxd3a","hoxc3a","hoxc4a","hoxb4a","hoxc6b","hoxb7a","hoxb10a")
FeaturePlot(seu, features = c(known_markers), ncol = 5, reduction  = 'tsne')
```

# Save data

```{r}
write.csv(nc.markers, "multiome/analysis_newref/clustering/results/NC_markers_RNAsoupx.csv")
saveRDS(seu, "multiome/analysis_newref/clustering/rds/seuobj_rna/seu_RNAsoupx_NC.rds")
gc()
```

# Technical

```{r}
sessionInfo()
```
